# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "ruanshiron/centos-6.6-with-xorp"
  config.ssh.username = "root"
  config.ssh.password = "vagrant"
  config.vm.network "private_network", virtualbox__intnet: "intnet3"
  config.vm.network "private_network", virtualbox__intnet: "intnet"

  config.vm.provision "shell", inline: <<-SHELL
    echo "NETWORKING=yes\nHOSTNAME=R4\nIPV6FORWARDING=yes\nRES_OPTIONS=\"single-request-reopen\"" > /etc/sysconfig/network

    echo "DEVICE=eth3\nONBOOT=yes\nIPV6ADDR=fec3::2/64\nNAME=eth3\nHWADDR=08:00:27:58:44:76\nTYPE=Ethernet\nIPV6INIT=yes\nIPV6_AUTOCONF=no\nIPV6_DEFROUTE=no\n" > /etc/sysconfig/network-scripts/ifcfg-eth3
    echo "DEVICE=eth4\nONBOOT=yes\nIPV6ADDR=fec4::1/64\nNAME=eth4\nHWADDR=08:00:27:AB:DD:80\nTYPE=Ethernet\nIPV6INIT=yes\nIPV6_AUTOCONF=no\nIPV6_DEFROUTE=no\n" > /etc/sysconfig/network-scripts/ifcfg-eth4

    echo "fec0::/64 via fec3::1\nfec1::/64 via fec3::1\nfec2::/64 via fec3::1" > /etc/sysconfig/network-scripts/route6-eth3
    echo "default via fec4::1" > /etc/sysconfig/network-scripts/route6-eth4

    service network restart

    wget -O multicast6.boot https://raw.githubusercontent.com/ruanshiron/ipv6-multicast-demo/master/mutlicast6.bootstrap.boot.example
    sed -in 's/ETH1NAME/eth3/g' ./multicast6.boot
    sed -in 's/ETH2NAME/eth4/g' ./multicast6.boot
    sed -in 's/ETH1IPV6/fec3::2/g' ./multicast6.boot
    sed -in 's/ETH2IPV6/fec4::1/g' ./multicast6.boot
    sed -in 's/ETH1LOCALIPV6/fe80::a00:27ff:fe58:4476/g' ./multicast6.boot
    sed -in 's/ETH2LOCALIPV6/fe80::a00:27ff:feab:dd80/g' ./multicast6.boot
  SHELL
end
